### PR TITLE
Add Travis CI

### PR DESCRIPTION
**Pull request by ChristophWurst**
This adds a basic Travis configuration that will build and test this middleware. Since the gotham version required for the current master branch has not been released yet, I've added it as git dependency.

### CODE REVIEW

**Comment by ChristophWurst** [comment]
Oh, @bradleybeddoes @smangelsdorf looks like Travis is not enabled for this repo.

**Comment by ChristophWurst** [comment]
> Since the gotham version required for the current master branch has not been released yet, I've added it as git dependency.

Looks like that's what @bradleybeddoes did in https://github.com/gotham-rs/middleware-diesel/commit/a613a63256b384b127bda9dc7c3cd3b13d93b0e4 too.

**Comment by smangelsdorf** [comment]
Closing/opening to attempt to trigger a build

**Comment by bradleybeddoes** [comment]
Seems to have [completed successfully](https://travis-ci.org/gotham-rs/middleware-diesel/builds/317650378) :+1:

Should we [enable coverage and allow nightly to fail?](https://github.com/gotham-rs/gotham/blob/master/.travis.yml#L24-L28)

**Comment by smangelsdorf** [comment]
> Should we enable coverage and allow nightly to fail?

Sounds like a good idea.

**Comment by ChristophWurst** [comment]
I can add coverage reports in a follow-up PR.

**Comment by bradleybeddoes** [comment]
Hey @ChristophWurst I am happy for coverage to come in a seperate PR.

Due to merge of #5 there is now conflict on this PR. Could you resolve so I can merge it?

**Comment by ChristophWurst** [comment]
> Due to merge of #5 there is now conflict on this PR. Could you resolve so I can merge it?

Done 😉

**Pull request merged**
